<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>es.nesi</groupId>
  <artifactId>NInterface</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties>
    <!-- Configura aquí tu versión de Java (ej. 17 o 21) -->
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
 	<!-- Jackson Core: Funcionalidades básicas de streaming -->
	<dependency>
	        <groupId>com.fasterxml.jackson.core</groupId>
	        <artifactId>jackson-core</artifactId>
	        <version>2.17.2</version>
	    </dependency>
	    <!-- Jackson Annotations: Para mapear propiedades si fuera necesario -->
	    <dependency>
	        <groupId>com.fasterxml.jackson.core</groupId>
	        <artifactId>jackson-annotations</artifactId>
	        <version>2.17.2</version>
	    </dependency>
	    <!-- Jackson Databind: El ObjectMapper para convertir JSON a Objetos -->
	    <dependency>
	        <groupId>com.fasterxml.jackson.core</groupId>
	        <artifactId>jackson-databind</artifactId>
	        <version>2.17.2</version>
	    </dependency>    
  </dependencies>  
  
</project>